# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Apps/Brontes/View/Brontes_main.ui'
#
# Created: Tue Sep 26 22:37:34 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_brontes_main(object):
    def setupUi(self, brontes_main):
        brontes_main.setObjectName("brontes_main")
        brontes_main.resize(996, 698)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(brontes_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_vertical_layout = QtWidgets.QVBoxLayout()
        self.top_vertical_layout.setObjectName("top_vertical_layout")
        self.top_horizontal_layout = QtWidgets.QHBoxLayout()
        self.top_horizontal_layout.setObjectName("top_horizontal_layout")
        self.cyc_icon = QtWidgets.QLabel(brontes_main)
        self.cyc_icon.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cyc_icon.setText("")
        self.cyc_icon.setPixmap(QtGui.QPixmap("../../../Core/config/icons/cyc_small.png"))
        self.cyc_icon.setObjectName("cyc_icon")
        self.top_horizontal_layout.addWidget(self.cyc_icon)
        self.show_shot_layout = QtWidgets.QFormLayout()
        self.show_shot_layout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.show_shot_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.show_shot_layout.setHorizontalSpacing(10)
        self.show_shot_layout.setObjectName("show_shot_layout")
        self.show_label = QtWidgets.QLabel(brontes_main)
        self.show_label.setObjectName("show_label")
        self.show_shot_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.show_label)
        self.show_comboBox = QtWidgets.QComboBox(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_comboBox.sizePolicy().hasHeightForWidth())
        self.show_comboBox.setSizePolicy(sizePolicy)
        self.show_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.show_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.show_comboBox.setObjectName("show_comboBox")
        self.show_shot_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.show_comboBox)
        self.shot_label = QtWidgets.QLabel(brontes_main)
        self.shot_label.setObjectName("shot_label")
        self.show_shot_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.shot_label)
        self.shot_comboBox = QtWidgets.QComboBox(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_comboBox.sizePolicy().hasHeightForWidth())
        self.shot_comboBox.setSizePolicy(sizePolicy)
        self.shot_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.shot_comboBox.setObjectName("shot_comboBox")
        self.show_shot_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shot_comboBox)
        self.top_horizontal_layout.addLayout(self.show_shot_layout)
        self.vertical_divider = QtWidgets.QFrame(brontes_main)
        self.vertical_divider.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_divider.setObjectName("vertical_divider")
        self.top_horizontal_layout.addWidget(self.vertical_divider)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_horizontal_layout.addItem(spacerItem)
        self.top_vertical_layout.addLayout(self.top_horizontal_layout)
        self.verticalLayout_2.addLayout(self.top_vertical_layout)
        self.divider_top = QtWidgets.QFrame(brontes_main)
        self.divider_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.divider_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider_top.setObjectName("divider_top")
        self.verticalLayout_2.addWidget(self.divider_top)
        self.mid_horizontal_layout = QtWidgets.QHBoxLayout()
        self.mid_horizontal_layout.setObjectName("mid_horizontal_layout")
        self.poly_label = QtWidgets.QLabel(brontes_main)
        self.poly_label.setObjectName("poly_label")
        self.mid_horizontal_layout.addWidget(self.poly_label)
        self.poly_lineEdit = QtWidgets.QLineEdit(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poly_lineEdit.sizePolicy().hasHeightForWidth())
        self.poly_lineEdit.setSizePolicy(sizePolicy)
        self.poly_lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.poly_lineEdit.setSizeIncrement(QtCore.QSize(0, 35))
        self.poly_lineEdit.setBaseSize(QtCore.QSize(0, 12))
        self.poly_lineEdit.setObjectName("poly_lineEdit")
        self.mid_horizontal_layout.addWidget(self.poly_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mid_horizontal_layout.addItem(spacerItem1)
        self.search_lineEdit = QtWidgets.QLineEdit(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_lineEdit.setSizePolicy(sizePolicy)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.search_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.mid_horizontal_layout.addWidget(self.search_lineEdit)
        self.search_button = QtWidgets.QToolButton(brontes_main)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Core/config/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon)
        self.search_button.setObjectName("search_button")
        self.mid_horizontal_layout.addWidget(self.search_button)
        self.verticalLayout_2.addLayout(self.mid_horizontal_layout)
        self.divider = QtWidgets.QFrame(brontes_main)
        self.divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider.setObjectName("divider")
        self.verticalLayout_2.addWidget(self.divider)
        self.bottom_verticalLayout = QtWidgets.QVBoxLayout()
        self.bottom_verticalLayout.setObjectName("bottom_verticalLayout")
        self.bottom_horizontalLayout = QtWidgets.QHBoxLayout()
        self.bottom_horizontalLayout.setObjectName("bottom_horizontalLayout")
        self.types_listWidget = QtWidgets.QListWidget(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.types_listWidget.sizePolicy().hasHeightForWidth())
        self.types_listWidget.setSizePolicy(sizePolicy)
        self.types_listWidget.setMaximumSize(QtCore.QSize(180, 16777215))
        self.types_listWidget.setSizeIncrement(QtCore.QSize(10, 0))
        self.types_listWidget.setBaseSize(QtCore.QSize(10, 0))
        self.types_listWidget.setObjectName("types_listWidget")
        self.bottom_horizontalLayout.addWidget(self.types_listWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_2 = QtWidgets.QListWidget(brontes_main)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_4.addWidget(self.listWidget_2)
        self.textBrowser = QtWidgets.QTextBrowser(brontes_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.bottom_horizontalLayout.addLayout(self.verticalLayout_4)
        self.Detail_GroupBox = QtWidgets.QGroupBox(brontes_main)
        self.Detail_GroupBox.setFlat(False)
        self.Detail_GroupBox.setObjectName("Detail_GroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Detail_GroupBox)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon_detail = QtWidgets.QLabel(self.Detail_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_detail.sizePolicy().hasHeightForWidth())
        self.icon_detail.setSizePolicy(sizePolicy)
        self.icon_detail.setMinimumSize(QtCore.QSize(200, 100))
        self.icon_detail.setScaledContents(True)
        self.icon_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_detail.setObjectName("icon_detail")
        self.verticalLayout.addWidget(self.icon_detail)
        self.detail_labels_groupbox = QtWidgets.QGridLayout()
        self.detail_labels_groupbox.setObjectName("detail_labels_groupbox")
        self.version_detail_label = QtWidgets.QLabel(self.Detail_GroupBox)
        self.version_detail_label.setObjectName("version_detail_label")
        self.detail_labels_groupbox.addWidget(self.version_detail_label, 3, 0, 1, 1)
        self.task_detail_label = QtWidgets.QLabel(self.Detail_GroupBox)
        self.task_detail_label.setObjectName("task_detail_label")
        self.detail_labels_groupbox.addWidget(self.task_detail_label, 2, 0, 1, 1)
        self.task_detail_data = QtWidgets.QLabel(self.Detail_GroupBox)
        self.task_detail_data.setObjectName("task_detail_data")
        self.detail_labels_groupbox.addWidget(self.task_detail_data, 2, 1, 1, 1)
        self.name_detail_data = QtWidgets.QLabel(self.Detail_GroupBox)
        self.name_detail_data.setObjectName("name_detail_data")
        self.detail_labels_groupbox.addWidget(self.name_detail_data, 0, 1, 1, 1)
        self.type_detail_label = QtWidgets.QLabel(self.Detail_GroupBox)
        self.type_detail_label.setObjectName("type_detail_label")
        self.detail_labels_groupbox.addWidget(self.type_detail_label, 1, 0, 1, 1)
        self.name_detail_label = QtWidgets.QLabel(self.Detail_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_detail_label.sizePolicy().hasHeightForWidth())
        self.name_detail_label.setSizePolicy(sizePolicy)
        self.name_detail_label.setObjectName("name_detail_label")
        self.detail_labels_groupbox.addWidget(self.name_detail_label, 0, 0, 1, 1)
        self.type_detail_data = QtWidgets.QLabel(self.Detail_GroupBox)
        self.type_detail_data.setObjectName("type_detail_data")
        self.detail_labels_groupbox.addWidget(self.type_detail_data, 1, 1, 1, 1)
        self.version_detail_data = QtWidgets.QLabel(self.Detail_GroupBox)
        self.version_detail_data.setObjectName("version_detail_data")
        self.detail_labels_groupbox.addWidget(self.version_detail_data, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.detail_labels_groupbox)
        self.Version_detail_listWidget = QtWidgets.QListWidget(self.Detail_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Version_detail_listWidget.sizePolicy().hasHeightForWidth())
        self.Version_detail_listWidget.setSizePolicy(sizePolicy)
        self.Version_detail_listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.Version_detail_listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Version_detail_listWidget.setObjectName("Version_detail_listWidget")
        self.verticalLayout.addWidget(self.Version_detail_listWidget)
        self.bottom_horizontalLayout.addWidget(self.Detail_GroupBox)
        self.bottom_verticalLayout.addLayout(self.bottom_horizontalLayout)
        self.verticalLayout_2.addLayout(self.bottom_verticalLayout)

        self.retranslateUi(brontes_main)
        QtCore.QMetaObject.connectSlotsByName(brontes_main)

    def retranslateUi(self, brontes_main):
        brontes_main.setWindowTitle(QtWidgets.QApplication.translate("brontes_main", "Form", None, -1))
        self.show_label.setText(QtWidgets.QApplication.translate("brontes_main", "Show", None, -1))
        self.shot_label.setText(QtWidgets.QApplication.translate("brontes_main", "Shot", None, -1))
        self.poly_label.setText(QtWidgets.QApplication.translate("brontes_main", "Polyphemus ", None, -1))
        self.search_button.setText(QtWidgets.QApplication.translate("brontes_main", "...", None, -1))
        self.icon_detail.setText(QtWidgets.QApplication.translate("brontes_main", "icon Asset", None, -1))
        self.version_detail_label.setText(QtWidgets.QApplication.translate("brontes_main", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#00557f;\">Version</span></p></body></html>", None, -1))
        self.task_detail_label.setText(QtWidgets.QApplication.translate("brontes_main", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#00557f;\">Task</span></p></body></html>", None, -1))
        self.task_detail_data.setText(QtWidgets.QApplication.translate("brontes_main", "_*_", None, -1))
        self.name_detail_data.setText(QtWidgets.QApplication.translate("brontes_main", "_*_", None, -1))
        self.type_detail_label.setText(QtWidgets.QApplication.translate("brontes_main", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#00557f;\">Type</span></p></body></html>", None, -1))
        self.name_detail_label.setText(QtWidgets.QApplication.translate("brontes_main", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#00557f;\">Name</span></p></body></html>", None, -1))
        self.type_detail_data.setText(QtWidgets.QApplication.translate("brontes_main", "_*_", None, -1))
        self.version_detail_data.setText(QtWidgets.QApplication.translate("brontes_main", "_*_", None, -1))

